name = "Vyvoj"
uuid = "b87271fa-763f-41e2-9562-e21bb3e7007d"
version = "0.1.6"
authors = ["Martin"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "1.12"

Dates = "1"
Pkg = "1.12"
